[[pages]]
name = "Home"
path = "main.py"

[[pages]]
name = "Landry"
icon = ""
is_section = true

[[pages]]
path = "pages/landry-summary.py"
name = "Landry Achievement Summary"
icon=":ğŸ“ˆ:"

# [[pages]]
# path = "pages/landry-domain.py"
# name = "Landry Domain Summary"
# icon = "ğŸ“š"

[[pages]]
path = "pages/landry-ai.py"
name = "Landry Assessment Index"
icon = "ğŸ¯"

# [[pages]]
# path = ""
# name = "SPS Playground"
# icon = "ğŸ›"

[[pages]]
name = "Behrman"
icon = ""
is_section = true

[[pages]]
path = "pages/behrman-summary.py"
name = "Behrman Achievement Summary"
icon=":ğŸ“ˆ:"

# [[pages]]
# path = "pages/behrman-domain.py"
# name = "Behrman Domain Summary"
# icon = "ğŸ“š"

[[pages]]
path = "pages/behrman-ai.py"
name = "Behrman Assessment Index"
icon = "ğŸ¯"

# [[pages]]
# path = ""
# name = "SPS Playground"
# icon = "ğŸ›"